# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Core'
    pod 'IQKeyboardManager'
    pod 'Firebase/Storage'
    pod 'AlamofireImage'
    pod 'Alamofire'

  target 'ChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppUITests' do
    # Pods for testing
  end

end
